<a href="https://colab.research.google.com/github/stevejoy-9381/googlecolab-/blob/main/find_best_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.datasets import load_iris
flow=load_iris()

In [ ]:
df=pd.DataFrame(flow.data,columns=flow.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [ ]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [ ]:
df['target']=flow.target
df['target']=df['target'].apply(lambda x:flow.target_names[x])
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [ ]:
x=df.drop(['target'],axis='columns')
y=df.target

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [ ]:
from sklearn.svm import SVC
model=SVC()
model.fit(X_train,y_train)

SVC()

In [ ]:
model.score(X_test,y_test)

1.0

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
from sklearn import svm

In [ ]:
cross_val_score(svm.SVC(kernel='linear',C=10,gamma='auto'),x,y,cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [ ]:
cross_val_score(svm.SVC(kernel='rbf',C=10,gamma='auto'),x,y, cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [ ]:
cross_val_score(svm.SVC(kernel='rbf',C=20,gamma='auto'),x,y, cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [ ]:
cross_val_score(svm.SVC(kernel='linear',C=20,gamma='auto'),x,y,cv=5)

array([1.        , 1.        , 0.9       , 0.93333333, 1.        ])

In [ ]:
import numpy as np

In [ ]:
kernal=['rbf,linear']
cv=[10,20,30]
avg_scores={}
for kval in kernal:
  for cva in cv:
    cv_scores=cross_val_score(svm.SVC(kernel=kval,C=cva,gamma='auto'),x,y,cv=5)
    avg_scores[kval + '_' + str(cva)] = np.average(cv_scores)
avg_scores


ValueError: 
All the 5 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 1382, in wrapper
    estimator._validate_params()
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVC must be a str among {'linear', 'precomputed', 'poly', 'sigmoid', 'rbf'} or a callable. Got 'rbf,linear' instead.


In [ ]:
kernels = ['rbf', 'linear']
C = [1,10,20]
avg_scores = {}
for kval in kernels:
    for cval in C:
        cv_scores = cross_val_score(svm.SVC(kernel=kval,C=cval,gamma='auto'),x,y, cv=5)
        avg_scores[kval + '_' + str(cval)] = np.average(cv_scores)

avg_scores

{'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666}

In [ ]:
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(svm.SVC(gamma='auto'), {
    'C': [1,10,20],
    'kernel': ['rbf','linear']
}, cv=5, return_train_score=False)
clf.fit(x,y)
result=clf.cv_results_
result

{'mean_fit_time': array([0.00399189, 0.00296111, 0.00283566, 0.00292158, 0.00586405,
        0.00486174]),
 'std_fit_time': array([1.19428926e-03, 1.33441105e-04, 5.71018420e-05, 1.86205979e-04,
        1.49668816e-03, 4.32300199e-04]),
 'mean_score_time': array([0.00291476, 0.00218115, 0.00207276, 0.00209136, 0.00377331,
        0.00398574]),
 'std_score_time': array([6.98582314e-04, 8.89721917e-05, 6.12960025e-05, 9.24874070e-05,
        2.57451999e-04, 4.79410016e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20

In [ ]:
df=pd.DataFrame(result)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_C  \
0       0.003992      0.001194         0.002915        0.000699        1   
1       0.002961      0.000133         0.002181        0.000089        1   
2       0.002836      0.000057         0.002073        0.000061       10   
3       0.002922      0.000186         0.002091        0.000092       10   
4       0.005864      0.001497         0.003773        0.000257       20   
5       0.004862      0.000432         0.003986        0.000479       20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6

In [ ]:
df[['param_C','params','mean_test_score']]

param_C                         params  mean_test_score
0        1      {'C': 1, 'kernel': 'rbf'}         0.980000
1        1   {'C': 1, 'kernel': 'linear'}         0.980000
2       10     {'C': 10, 'kernel': 'rbf'}         0.980000
3       10  {'C': 10, 'kernel': 'linear'}         0.973333
4       20     {'C': 20, 'kernel': 'rbf'}         0.966667
5       20  {'C': 20, 'kernel': 'linear'}         0.966667

In [ ]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [ ]:
clf.best_score_

0.9800000000000001

In [ ]:

from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(svm.SVC(gamma='auto'), {
        'C': [1,10,20],
        'kernel': ['rbf','linear']
    },
    cv=5,
    return_train_score=False,
    n_iter=2
)
rs.fit(x,y)
pd.DataFrame(rs.cv_results_)[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       20       linear         0.966667
1        1       linear         0.980000